menu:
  首页: { id: index, url: /blog/ }
  归档: { id: archives, url: /blog/archives }
  标签: { id: tags, url: /blog/tags }
  分类: { id: categories, url: /blog/categories }
  链接: { id: links, url: /blog/links }
  关于: { id: curriculumvitae, url: /aboutme/ }

#github: ghw

background-root: https://dn-glibs.qbox.me/blog/images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]
cdn-jquery: //dn-glibs.qbox.me/jquery-2.1.4/
cdn-bootstrap: //dn-glibs.qbox.me/bootstrap-3.3.4/
cdn-opt: //dn-glibs.qbox.me/blog/

avatar: /blog/images/avatar.gif

#### Comment
duoshuo:
  short_name: gehaowu			         ## duoshuo short name.
                                         ## refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d
disqus:
  short_name: gehaowu			         ## disqus short name.

rss: /blog/atom.xml	                     ## if any...