menu:
  首页: { id: index, url: /blog/ }
  归档: { id: archives, url: /blog/archives }
  标签: { id: tags, url: /blog/tags }
  分类: { id: categories, url: /blog/categories }
  关于: { id: curriculumvitae, url: /aboutme/ }
  链接: { id: links, url: /blog/links }

github: ghw

background-root: /blog/images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]

avatar: /blog/images/avatar.gif

#### Comment
duoshuo: 
  short_name: gehaowu			         ## duoshuo short name.
                                         ## refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d

rss: /blog/atom.xml	                     ## if any...