menu:
  首页: { id: index, url: /notes20150626.old/ }
  归档: { id: archives, url: /notes20150626.old/archives }
  标签: { id: tags, url: /notes20150626.old/tags }
  分类: { id: categories, url: /notes20150626.old/categories }
  链接: { id: links, url: /notes20150626.old/links }
  关于: { id: curriculumvitae, url: /aboutme/ }

#github: ghw

background-root: https://dn-glibs.qbox.me/blog/images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]
cdn-jquery: //dn-glibs.qbox.me/jquery-2.1.4/
cdn-bootstrap: //dn-glibs.qbox.me/bootstrap-3.3.4/
cdn-opt: //dn-glibs.qbox.me/blog/
cdn-respond: //dn-glibs.qbox.me/Respond-1.4.2/
cdn-html5shiv: //dn-glibs.qbox.me/html5shiv-3.7.2/

avatar: /notes20150626.old/images/avatar.gif

#### Comment
duoshuo:
  short_name: gehaowu			         ## duoshuo short name.
                                         ## refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d
disqus:
  short_name: gehaowu			         ## disqus short name.

rss: /notes20150626.old/atom.xml	                     ## if any...