# Header
menu:
  主页: /notes/
  归档: /notes/archives
  关于我: /resume/
rss: /notes/atom.xml

# Content
excerpt_link: 阅读全文 »
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
- archive
- recent_posts
- links

# Miscellaneous
google_analytics: UA-65013365-1
favicon: ../favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

tinysou: true