# Header
menu:
  Home: /notes/
  Archives: /notes/archives
rss: /notes/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Miscellaneous
google_analytics:
favicon: ../favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: